Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -24,14 +24,23 @@ publish:
         exit 1;
       fi
 release:
-  image: 
-    name: gitlab/glab
-    entrypoint: [""]
+  image: curlimages/curl:latest
   stage: deploy
+  variables:
+    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/releases?job_token=$CI_JOB_TOKEN"
   script:
     - git log --oneline --pretty=format:"%h %s" $(git describe --tags --abbrev=0 @^)..@ > changelog.txt
-    - glab auth login -t $CI_JOB_TOKEN -h $CI_SERVER_HOST
-    - glab release create $CI_COMMIT_TAG -F changelog.txt
+    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
+    - response=$(curl -X POST -s -w "\n%{http_code}" $insecure --form "tag_name=$CI_COMMIT_TAG" --form "description=$(cat changelog.txt)" $URL)
+    - code=$(echo "$response" | tail -n 1)
+    - body=$(echo "$response" | head -n 1)
+    # Output state information
+    - if [ $code -eq 201 ]; then
+        echo "Package created - Code $code - $body";
+      else
+        echo "Could not create package - Code $code - $body";
+        exit 1;
+      fi
   only:
     - tags  # please mention the "s" compared to Sergio Tomasello's solution
   except:
